### ISSUE TITLE
Interface to group 2

### ISSUE THREAD

**Issue by nbasargin** [MusicConnectionMachine/StructuredData#13]
Hey group 1!
Group 2 would like to know how to get data from the structured sources that you process. 

*Currently* we are interested in the *vocabulary* (terms relevant to classical music) that we should use to scan the unstructured sources. 

*Later* we would like to now how both our groups are going to combine the data and direct it to groups 3 & 4.

**Comment by ShilpaGhanashyamGore** [comment]
@nyxathid 
1.We are implementing a PostGreSql db .We can return json objects for your queries.
2.It will be great if you can give us some example queries .
3.We are going to create the database and populating it with the data we collect.You will be importing the data extracted from unstructured sources into the database .

**Comment by nbasargin** [comment]
2. Group 2 needs a list of all relevant terms (like names of composers, bands, music genres, recordings, ...)
It would be nice to get a JSON like:
```
{ terms : [
   { type: "composer"; value : "Mozart"},
   { type: "band"; value : "ACDC"},
   ...
] }
```

3. Do you already have some general database structure? What kind of data can we provide you?

**Comment by angelinrashmi2000** [comment]
Hey Group 2 
We have attached the list of keywords for artist entity that we have extracted from 3 sources 
1.Dbpedia
2.MusicBrainz
3.Allmusic
The output JSON file for these databases are in different format. We have included a Readme file in each folder describing the source and the format. Let us know if you have any more questions. 
[Data for Team 2.zip](https://github.com/MusicConnectionMachine/StructuredData/files/835308/Data.for.Team.2.zip)

**Comment by gyachdav** [comment]
Hello group 1.  As a rule of thumb you should handle any data exchange by providing an API to access your data. This is the dynamic universally and continuously available way for you to share data (even if seemingly this is a one time transaction)

**Comment by ShilpaGhanashyamGore** [comment]
@gyachdav  : Thank you for the feedback !
Yes , we will provide a REST API for  Group 2 (deals with unstructured  data ) with GET,UPDATE and POST APIs so that they can use the keywords for searching and add to list when they find new words .
Work is in progress , I will share the APIs once it is done . 
API will return the details of a composer /artist in the following fashion 
```
{
"name":"Ludwig August Lebrun",
"Pseudonym":[],
"Work":["Concerto for oboe & orchestra No. 3 in C major","Concerto for oboe & orchestra No. 1 in D minor","Concerto for oboe & orchestra No. 2 in G minor","Work(s)","Concerto for oboe & orchestra No. 5 in C major","Concerto for oboe & orchestra No. 4 in B flat major","Concerto for oboe & orchestra No. 6 in F major","Piano Sonata in F major, Op. 1/3","Concerto for oboe & orchestra No. 7 in F major","Concerto for oboe, 2 horns ad libitum & strings No. 4 in C major","Concerto for clarinet & orchestra in B flat major"],
"release":[],
"Source_link":"http://www.allmusic.com/artist/ludwig-august-lebrun-mn0001198697"
}
```
@nyxathid

**Comment by pfent** [comment]
@ShilpaGhanashyamGore you should use a json checker / formatter like https://jsonformatter.curiousconcept.com/

Also, can you please put code in code blocks, like described here: https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by ShilpaGhanashyamGore** [comment]
@nyxathid : Here is the list of RestAPIs that we shall support :
[REST_END_Points_for group2.xlsx](https://github.com/MusicConnectionMachine/StructuredData/files/837947/REST_END_Points_for.group2.xlsx)

**Comment by ShilpaGhanashyamGore** [comment]
@pfent nt : Can you provide me with an example of code fencing in nodejs ?I applied ``` but node says 
TypeError: "" is not a function.I scouted the internet for examples did not find any.
Exam of my code :
```
app.post("/entities/addEntity",function(req,res){
});
```

**Comment by kordianbruck** [comment]
@ShilpaGhanashyamGore ``` is not for nodejs, but for posting code here in Github (what @pfent said previously)

Or what exactly you mean by "code fencing"?

**Comment by ShilpaGhanashyamGore** [comment]
No I mean to ask if it was a node js feature because I got compilation errors . Thanks for clearing it for me !

**Comment by ShilpaGhanashyamGore** [comment]
[REST_END_Points_for group2.xlsx](https://github.com/MusicConnectionMachine/StructuredData/files/838326/REST_END_Points_for.group2.xlsx)
@nyxathid :updated REST endpoint description.Please feel free to ask us questions if any .
@TimHenkelmann and myself can answer them for you .

**Comment by nbasargin** [comment]
@ShilpaGhanashyamGore Thanks!
