### ISSUE TITLE
Edit your part of presentation

### ISSUE THREAD

**Issue by metavaults** [MusicConnectionMachine/StructuredData#16]
I have sent you the presentation of the theorerical part, please take a look at it, edit if needed and sens me back (today evening at latest!)

**Comment by ShilpaGhanashyamGore** [comment]
I am working on the Interface to Group 2 issue .I can send in comments latest by 14-Mar EOD.

**Comment by kordianbruck** [comment]
Please use Gitter / other channels for such communications regarding presentations. Issues are project related things only please.
https://github.com/MusicConnectionMachine/StructuredData/issues/16#issuecomment-286091570
