### ISSUE TITLE
Scripts to populate PostGreSql from Json files containing extracted data 

### ISSUE THREAD

**Issue by ShilpaGhanashyamGore** [MusicConnectionMachine/StructuredData#18]

**Comment by angelinrashmi2000** [comment]
Shilpa I am already working on it

**Comment by ShilpaGhanashyamGore** [comment]
Oh did not know that .
I have created a "entities" table in postgres db .We will expose API for this DB to group 2 .
Please populate that table .

**Comment by angelinrashmi2000** [comment]
OK I will populate the entity table using the script

**Comment by kordianbruck** [comment]
@angelinrashmi2000 thats why you should add a [WIP] (work in progress) pull request or reference this issue from the commit or even assign it the issue when you start working.

**Comment by kordianbruck** [comment]
@angelinrashmi2000 Whats the progress here? Did you complete this? Is this now done in the API project? What are the Pull Requests?

**Comment by sacdallago** [comment]
This can be closed, I think. There's no direct access to PG anyway.
But yes: the scripts need to be written

**Comment by TimHenkelmann** [comment]
Closing this issue as this will be handled in the cli
