### ISSUE TITLE
Define vocabulary 

### ISSUE THREAD

**Issue by TimHenkelmann** [MusicConnectionMachine/StructuredData#2]
Define a vocabulary of entities based on data from structured sources. The vocabulary will be used and updated by Team 2, so this issue should be completed rather early.

**Comment by kordianbruck** [comment]
Maybe you can make use of the other team's mockup somehow?
https://github.com/MusicConnectionMachine/VisualizationG5/pull/7/files

**Comment by kordianbruck** [comment]
@TimHenkelmann we should be done with this task by now. If so, please close and reference any pull request regardings this.

**Comment by TimHenkelmann** [comment]
This was already discussed with Team 2 last week. Closed as done!
