### ISSUE TITLE
Server hosting

### ISSUE THREAD

**Issue by kordianbruck** [MusicConnectionMachine/StructuredData#25]
Initial hosting of the PostgreDB + NodeJS Server

**Comment by kordianbruck** [comment]
@sacdallago can we give the students access to azure or a different server to get a "testing site" going?

**Comment by sacdallago** [comment]
@kordianbruck they have an azure VM already up and working for their testing purposes.

You guys should set up a docker-compose file detailing which images are needed to run the scripts? Eg. Postgres, node.

I think you need to write two `Dockerfile`s, one for the API, one for Postgres (that automatically loads the table definitions and maybe an .sql data dump that is stored somewhere /not in the repo/ and updated periodically. Additionally you can export all of your scripts as a node CLI tool. Ideally:
```bash
$ npm install -g musicConnectionCrawler
$ musicConnectionCrawler --help

  musicConnectionCraweler v 1.0

  Required:
  --script scrapeWorks, scrapeReleases

  Optionals:
  [-- output] /path/to/folder/nameOfFile.json
  [-- api] http[s]://api.domain.com

$ musicConnectionCrawler --script scrapeWorks --api https://hello.party.people
```

as an npm package with

**Comment by kordianbruck** [comment]
@sacdallago great!

The machine does not seem to be running / work. One can't ping the IP (Should not depend on closed ports as its ICMP) - is it turned off?

Cont. discussion from https://github.com/MusicConnectionMachine/StructuredData/pull/24#issuecomment-286894952
@ShilpaGhanashyamGore

**Comment by sacdallago** [comment]
@kordianbruck na, na, the machine is up and running, no worries!

https://blogs.msdn.microsoft.com/mast/2014/06/22/use-port-pings-instead-of-icmp-to-test-azure-vm-connectivity/

http://serverfault.com/questions/782140/how-can-i-enable-ping-on-an-azure-linux-vm

**Comment by ShilpaGhanashyamGore** [comment]
@sacdallago : We tried to use psping.exe to test the port .But again request timed out .
Can you please resolve this for us so we test our api on the test machine .
Thank you !

**Comment by pfent** [comment]
```
$ nmap testmusicmachine.northeurope.cloudapp.azure.com -Pn

Starting Nmap 7.40 ( https://nmap.org ) at 2017-03-21 11:17 CET
Nmap scan report for testmusicmachine.northeurope.cloudapp.azure.com (52.178.131.239)
Host is up (0.19s latency).
Not shown: 999 filtered ports
PORT   STATE SERVICE
53/tcp open  domain
```

The machine is definitely up, but rejecting almost everything...

**Comment by kordianbruck** [comment]
@sacdallago ideas?

**Comment by sacdallago** [comment]
Ports 80 and 443 have been opened on the test machine. But this should not be necessary anymore? You should port all of the logic to docker cloud?

Maybe we can talk in person?

**Comment by kordianbruck** [comment]
@ShilpaGhanashyamGore did you resolve this issue? Long time no update...

**Comment by ShilpaGhanashyamGore** [comment]
@kordianbruck  @sacdallago  : We are trying to setup the workflow where  in we have the docker tool support in MS Visual Studio which docker image and after the image is pushed into the docker registry we pull the same on the Azure Linux VM and run it in the VM.

But we are having problems at the first step itself. We are unable to integrate docker tools into MS Visual Studio 2017 & 2015 both community and enterprise edition( the tool kit is not offered within installation environment of VS instead we have sperately run the exe and integrate in VS)  due to installation errors which are not getting resolved though we are trying our best.
We tried this on 2 laptops and are observing different error behavior .
Any advise or pointers for us?

**Comment by kordianbruck** [comment]
@ShilpaGhanashyamGore yes, don't use those tools but write the configuration files yourself. Take some inspiration from: https://github.com/MusicConnectionMachine/VisualizationG6/blob/develop/Dockerfile

**Comment by ShilpaGhanashyamGore** [comment]
@kordianbruck :Yes . we have a dockerfile for our app .
[Dockerfile.txt](https://github.com/MusicConnectionMachine/StructuredData/files/874055/Dockerfile.txt)

**Comment by kordianbruck** [comment]
@ShilpaGhanashyamGore why is this not in the repository? Why are you using Webpack? Whaaat?

**Comment by ShilpaGhanashyamGore** [comment]
@kordianbruck : Yes webpack is not needed it is for front end .I removed it .
The first image has been pushed into Docker Hub and the Azure Linux VM has been hooked to it.
The app is running but not functional .
https://hub.docker.com/r/musicconnectionmachine/structureddata/tags/
http://structuredmusicdata.azurewebsites.net/
Also , Azure VM directs you to VS 2017 professional free trial for 90 days , guess what that is no better than community/enterprise w.r.t the fancy built in docker support that was shown in the demo. This is just an FYI.

**Comment by sacdallago** [comment]
@ShilpaGhanashyamGore can you come this Friday and we take some time to go over all of this together? Like 2h or something? cc @TimHenkelmann

**Comment by ShilpaGhanashyamGore** [comment]
@sacdallago I can come today as well  .I want to really get this done .
Friday is too late :-(

**Comment by TimHenkelmann** [comment]
@sacdallago same here!

**Comment by kordianbruck** [comment]
@ShilpaGhanashyamGore @TimHenkelmann 1.9.59 @ 15:30 please today. Thanks.

**Comment by ShilpaGhanashyamGore** [comment]
Great ! Thank you .See you at 15.30.

**Comment by TimHenkelmann** [comment]
See you later!

**Comment by nbasargin** [comment]
What is the current state of the DB right now? Is it already running somewhere?

**Comment by sacdallago** [comment]
@nyxathid you should have a test version deployed somewhere on Azure

**Comment by pfent** [comment]
Today, we finally gave some people access to the database…
The database is running on 13.74.11.216, listening only on localhost. So you need to tunnel everything through ssh!  
@nyxathid should already have access;  
@ShilpaGhanashyamGore and @TimHenkelmann: I just added your ssh public key from github to the machine (handy dandy: https://github.com/TimHenkelmann.keys 🎉 ). You should now be able to SSH into the machine, using this public key:
```
$ ssh students@13.74.11.216
```

Could you please confirm, your access is working and you can reach the server via SSH?
You can also find the postgres credentials in the home directory, so please also make sure you configure access to postgres

**Comment by TimHenkelmann** [comment]
@pfent Yep, I can connect to the machine 13.74.11.216. Is the other IP above a typo?  (xx.47.xx.xxx => xx.74.xx.xxx)
And I'm not sure if I got your last point... do you mean that we should update the credentials in our config file such that they match the one in the postgres credentials file?

**Comment by ShilpaGhanashyamGore** [comment]
@pfent , @kordianbruck  : Please add this key .Thank you 

[publicKey_JS.zip](https://github.com/MusicConnectionMachine/StructuredData/files/903530/publicKey_JS.zip)

**Comment by pfent** [comment]
@ShilpaGhanashyamGore that's the same key as [on github](https://github.com/ShilpaGhanashyamGore.keys), isn't it?

I already added it yesterday, so you already should have access

@TimHenkelmann Pssssst :zipper_mouth_face:. Sneakily edited it :)

**Comment by pfent** [comment]
@MusicConnectionMachine/group-1 The server should be up and running now?
What's your status on this? We kinda really need some data in the DB, so the relationships group can start spinning up their processing clusters…

I'd suggest we can close this Issue and you start working on #49 and get some data into the database for #63

**Comment by nbasargin** [comment]
Yes, some real data in DB on Azure would be great! :heart_eyes:

**Comment by TimHenkelmann** [comment]
@pfent Well, I'm still working on connecting the different entities when we populate the db (ArtistComposedWork, ArtistPlayedInstrument, etc...) 
But we could already execute the cli as it is at the moment, then we would already have all the artists, work and releases as well as entities and the connection between entities/artists, entities/works, entities/releases.
How are we going to populate it anyway when it is only listening on localhost?

**Comment by pfent** [comment]
@TimHenkelmann The server is already exposing postgres publicly (that's why we changed the user/password), i.e. you should be able to connect directly to postgres without any SSH tunneling.

However, there's currently trouble with the Azure subscription and the VM is down. If I read Gitter correctly, the relationship guys burned through all of the associated money 💤

**Comment by kordianbruck** [comment]
Finished up. Got several Servers running.
