### ISSUE TITLE
Table Setup in Postgresql

### ISSUE THREAD

**Issue by angelinrashmi2000** [MusicConnectionMachine/StructuredData#26]
Define fields, key, constraints for all the entities and create the table.

**Comment by kordianbruck** [comment]
Please consider using an ORM: http://docs.sequelizejs.com/en/v3/

There will be a lot more to save, so using a ORM will save you a lot of time in the future!

**Comment by ShilpaGhanashyamGore** [comment]
Tim and I have created a schema (in PGAdmin 4) we have some open points . We can discuss this and create the schema today in VM

**Comment by TimHenkelmann** [comment]
Closing this issue as this is already implemented via Sequelize in the[api project](https://github.com/MusicConnectionMachine/api)
