### ISSUE TITLE
Allmusic: additional data source

### ISSUE THREAD

**Issue by ShilpaGhanashyamGore** [MusicConnectionMachine/StructuredData#29]
@vviro @sacdallago @kordianbruck @pfent 
We found a new data source for classical composers  :http://www.allmusic.com/genre/classical-ma0000002521/artists .This source has elaborate information about many classical composers .
We have a working script to crawl this source .
However there  are 2 main challenges :    
1.Data of Birth , Place of birth are in the of text unlike other sources 
2. HTML of main page lists only few classical composers .But when we google for "composer names taken from dbpedia + allmusic" we find their webpages .
Eg:
http://www.allmusic.com/genre/classical-ma0000002521/artists - is the main page
We do not find (to name  a few) when we crawl the main url and http://www.allmusic.com/artist/ is not a valid endpoint : 
http://www.allmusic.com/artist/alessandro-scarlatti-mn0001231509
http://www.allmusic.com/artist/carl-friedrich-abel-mn0001198334
http://www.allmusic.com/artist/domenico-alberti-mn0002385309
http://www.allmusic.com/artist/georg-philipp-telemann-mn0001456424 http://www.allmusic.com/artist/george-frederick-handel-mn0000805740
http://www.allmusic.com/artist/jean-jacques-rousseau-mn0001704978

**Comment by pfent** [comment]
So that source doesn't offer structured data through an API?

Then it's probably better suited as a source for group 1...

**Comment by sacdallago** [comment]
@pfent you mean @MusicConnectionMachine/group-2 ?

**Comment by kordianbruck** [comment]
#34 #36 
@ShilpaGhanashyamGore is this done? What is the status?

**Comment by ShilpaGhanashyamGore** [comment]
Yes done .Closing the issue .
