### ISSUE TITLE
Interface to Group3/4

### ISSUE THREAD

**Issue by ShilpaGhanashyamGore** [MusicConnectionMachine/StructuredData#30]
@Henni @simonzachau  @kordianbruck @sacdallago @vviro @pfent 

We want to know what are the kinds of queries we should expect from your module .
We can then created prepared statements to help queries return results faster .
If you can give us some sample queries then we can start preparing them already .
This greatly influences the design of our schema : the foreign keys and many more.

**Comment by sacdallago** [comment]
@MusicConnectionMachine/group-3 @MusicConnectionMachine/group-4 I think there is an open discussion somewhere about something similar? Makes sense to have @MusicConnectionMachine/group-2 here as well, since ideally you will all (group1/group2) serve the data in the same way and through the same api? Hopefully?

**Comment by Sandr0x00** [comment]
Do we get an API? I thought we have to get the data directly from the DB?
[Reference](https://github.com/MusicConnectionMachine/RelationshipsG4/blob/develop/documents/Architecture%20Overview.png) from our group.
[Reference](https://github.com/MusicConnectionMachine/RelationshipsG3/issues/10) from @MusicConnectionMachine/group-3.  (Like I understand it, group 3 also plans to fetch the data directly from db)

But we can agree on an API. If we agree on an API, do you give us the option to save our relationships in the DB, or do we have to do it ourselves?

Or do you mean, how you plan to save the data in the DB?
What data do you have? Composer - Music Piece? Or Composer - Source like described in the project description (Wolfgang Amadeus Mozart → [ https://musicbrainz.org/artist/b972f589-fb0e-474e-b64a-803b0364fa75, soruce2, …])?

**Comment by ShilpaGhanashyamGore** [comment]
Renaming the issue to "Interface to Group 3/4"

**Comment by Sandr0x00** [comment]
[Reference](https://github.com/MusicConnectionMachine/UnstructuredData/issues/50) to a similar topic.

**Comment by simonzachau** [comment]
this should be resolved by [the api](https://github.com/MusicConnectionMachine/api/issues/1)

**Comment by kordianbruck** [comment]
It really is resolved
