### ISSUE TITLE
Add REST API proposal to google doc 

### ISSUE THREAD

**Issue by TimHenkelmann** [MusicConnectionMachine/StructuredData#31]
We need to add our proposal for the REST API (including the entity structure + parameters)
 to the [google doc](https://docs.google.com/document/d/1TjBtrBpeD-v0Q_oqy_b2sM1i8mfR1qLu6cwPUkP8BBk/edit) where the other teams will also collaborate theirs.

**Comment by kordianbruck** [comment]
Please do this today! @MusicConnectionMachine/group-1

**Comment by TimHenkelmann** [comment]
was done back then
