### ISSUE TITLE
Setup REST API

### ISSUE THREAD

**Issue by TimHenkelmann** [MusicConnectionMachine/StructuredData#32]
We need to set up a REST API until Friday 12:00. This should be in compliance with the proposals in the [google doc](https://docs.google.com/document/d/1TjBtrBpeD-v0Q_oqy_b2sM1i8mfR1qLu6cwPUkP8BBk/edit)

**Comment by kordianbruck** [comment]
Are you guys planing on doing a proof on concept in this repo first, or are you directly going to implement it in the API repo? 

Looking at #24

**Comment by TimHenkelmann** [comment]
Closing this issue. It is going to get implemented directly in the API repo
