### ISSUE TITLE
Script to crawl MusicBrainz

### ISSUE THREAD

**Issue by ShilpaGhanashyamGore** [MusicConnectionMachine/StructuredData#4]
Try to find if ready scripts to crawl MusicBrainz are available .If not we make one

**Comment by metavaults** [comment]
Script is done.

**Comment by sacdallago** [comment]
When something is done in a commit, commit putting as last part of the commit message:

`blablabla closes #4`, where `#4` is the issue that is being closed. If that commit makes it into develop (aka, after the PR has been approved), the issue will close automatically. [more](https://help.github.com/articles/closing-issues-via-commit-messages/)
