### ISSUE TITLE
Sample Data for Groups 5/6

### ISSUE THREAD

**Issue by kordianbruck** [MusicConnectionMachine/StructuredData#40]
Maybe I'm missing it, but I can't seem to find it.

You guys need to give them some sample data that they can work with. Thanks!

**Comment by kordianbruck** [comment]
Also #63

**Comment by angelinrashmi2000** [comment]
This the sample data which has artist, release and works.
[Team5:6 2.zip](https://github.com/MusicConnectionMachine/StructuredData/files/894048/Team5.6.2.zip)

**Comment by kordianbruck** [comment]
@MusicConnectionMachine/group-5 @MusicConnectionMachine/group-6
