### ISSUE TITLE
Get this running on azure - #1 priority

### ISSUE THREAD

**Issue by kordianbruck** [MusicConnectionMachine/StructuredData#43]
So guys, we really need this to be deployed so teams 3/4 can start running on larger datasets and use your data. 

Here are the tasks/roadmap:

- [x] Get your CI running https://github.com/MusicConnectionMachine/StructuredData/issues/41
- [x] Setup docker for deployment https://github.com/MusicConnectionMachine/StructuredData/issues/42
- [x] Find a way to start a single file to start scraping data
- [x] Finalize your models in the API project
- [x] Connect to the DB and start populating the data
- [ ] Optimize  so you can grab even more data! (Use threads, more machines, be creative)

@TimHenkelmann  please organize the distribution of the tasks to your team members. 

# This is currently the number one priority!

Deadline / Milestone: Wednesday 29.03.2017 @ 18:00
We will have a Hangout session @ 18:15 where we will discuss your progress

**Comment by ShilpaGhanashyamGore** [comment]
@kordianbruck 
What is done : 
1.CLI app to local database connection is working , we are able to populate the database
2.Server hosted locally is able to connect to database and return the result for GET request
3. Server can take command line arguments which shall override default values to connect to local database

**Comment by kordianbruck** [comment]
Alrighty - lets close this for now then. Please create new issues for the still open things.

Thanks for the update! :dancer:
