### ISSUE TITLE
Connect API docker container to PostGreDB 

### ISSUE THREAD

**Issue by ShilpaGhanashyamGore** [MusicConnectionMachine/StructuredData#48]
For now , we connect API container with local PostgresDB .
Eventually we should be able to connect the docker API container running on web App service(in Azure) to  PostgreDb running on VM .

**Comment by ShilpaGhanashyamGore** [comment]
@krishenk , @kordianbruck  , @sacdallago  : right now we have docker-compose which forces docker api image to communicate with docker image of postgredb .But from what I understood in our discussion that is not our goal right now.
I think docker-compose should be added at a later stage and be removed for now .
Please comment .

**Comment by sacdallago** [comment]
You can remove everything docker-related from this repo for now. The stuff that you produce here is going to be exported as an npm script ;)

**Comment by ShilpaGhanashyamGore** [comment]
@sacdallago : I am sorry , I am talking of MusicConnectionMachine/API repository .I should have raised the question there .
Anyway my question is : we don't need docker-compose.yml in MusicConnectionMachine/API   .Reason being that we are not going to have our postgres database as docker image (atleast for near future) .Hence docker compose is not required .
Please confirm here so that @krishenk can remove it .
Thank you !

**Comment by sacdallago** [comment]
@ShilpaGhanashyamGore well, no. I would still leave it. It gives other developers an understanding of your system dependencies.

**Comment by sacdallago** [comment]
P.S.: closing the issue here, at this is the wrong repo and otherwise it generates confusion
