### ISSUE TITLE
Enable docker API container to expose the data in local db 

### ISSUE THREAD

**Issue by ShilpaGhanashyamGore** [MusicConnectionMachine/StructuredData#50]
Run the docker server image and connect to localDB .

**Comment by kordianbruck** [comment]
So this is about writing the API Endpoints right?

**Comment by ShilpaGhanashyamGore** [comment]
No , this is about running the docker server image and connecting to localDB .
My first comment is misplaced .

**Comment by kordianbruck** [comment]
@ShilpaGhanashyamGore maybe you can fix your first comment then by editing it?

**Comment by kordianbruck** [comment]
Guess this is finished @ShilpaGhanashyamGore as we have the final DB already up and running

Closing.
