### ISSUE TITLE
Script to crawl DBPedia

### ISSUE THREAD

**Issue by ShilpaGhanashyamGore** [MusicConnectionMachine/StructuredData#6]
Understand how the data from DBPedia can be crawled .Use ready scripts if available .Else make a script

**Comment by ShilpaGhanashyamGore** [comment]
@vviro :Python scripts given for DBPedia(in rostlab wikipage)  is basically for annotating a given text using the DBPedia ID.It employs 3 techniques DPBedia Spotlight and 2 others to perform the initial annotation.And then  it homogenizes the output from 3 tools before publishing the results . I dont understand how does it serve our purpose ?Please correct me if I am missing something.

**Comment by TimHenkelmann** [comment]
This is implemented in the pullrequest #14, #15, #23 and others
