### ISSUE TITLE
Data for group 2

### ISSUE THREAD

**Issue by nbasargin** [MusicConnectionMachine/StructuredData#63]
To start some serious testing group 2 needs relevant terms to search for. So far we have been using some dummy terms. Could you provide us some real data? 

Ideally, that should be a running database. I now that it could take some time, so a simple file with 100+ composers, 100+ pieces and a few other terms would be extremely helpful before the DB is running.

**Comment by vviro** [comment]
This is extremely important, please provide the data as quickly as possible. Any format would do: a plain text file is just fine, the main thing is this happens asap. If you have more than 100 entries, go ahead and export as much as possible. It should be possible to close this issue already today, right?

**Comment by metavaults** [comment]
@nyxathid, a few weeks ago we already provided you with the .json files that contain works, releases, and composers. We have shared them with you today on gitter again.

**Comment by pfent** [comment]
Also dropping [this](https://github.com/MusicConnectionMachine/StructuredData/files/893982/Team2.zip) here, since in my experience files in chats are lost quickly…

@MusicConnectionMachine/group-1, do you mind providing some textual documentation, in what those json files contain?

**Comment by TimHenkelmann** [comment]
@pfent Well, the ReleasesAPI.json, Works.json and Artists.json files contain the releases, works and artists scraped from musicbrainz and the other .json files in Artists contain composers and musicians from dbpedia ^^
Or what exactly do you have in mind when you refer to a "textual documentation"?

**Comment by kordianbruck** [comment]
Real data is up and running in the postgre to be used by group 2 - closing.
