### ISSUE TITLE
Website throttling / Scraping speed

### ISSUE THREAD

**Issue by kordianbruck** [MusicConnectionMachine/StructuredData#64]
Please supply what your findings are in terms of which services throttles scraping in which way?

Maybe we can contact the vendors and ask the to give us more speed or use multiple IPs to fetch data. 

e.g.:
* Google: 1 request from 1 IP every 5 seconds

**Comment by TimHenkelmann** [comment]
For Musicbrainz, it's [1 request per second](https://musicbrainz.org/doc/XML_Web_Service/Rate_Limiting). Also, "if your requests are coming in at 4 requests per second, we don't honour 25% of them and decline the other 75% - we decline 100% of them, until the rate drops to 1 per second or lower."

Regarding worldcat and dbpedia, I haven't found any official statement yet but I'll keep on looking!

**Comment by kordianbruck** [comment]
I guess this is obsolete now, as we were able to scrape everything? @TimHenkelmann 
Whats the experience?

**Comment by kordianbruck** [comment]
Not of interest any longer I think.

**Comment by TimHenkelmann** [comment]
Yep, obsolete!
