### ISSUE TITLE
How to handle invalid dates

### ISSUE THREAD

**Issue by TimHenkelmann** [MusicConnectionMachine/StructuredData#71]
From time to time, we only get partial dates like "1632" or "1742-03". When we try to populate the database with those entries, this results in an error:  "invalid input syntax for type date".
This is currently solved by just adding "-01-01" or "-01" to the date. Let's check if there exists a better way

**Comment by pfent** [comment]
Storing this as a date type is definitely the way to go. Personally, I wouldn't want to loose information in this progress, so you might want to add something like a date precision field `Y`/`M`/`D`

**Comment by kordianbruck** [comment]
I mean it would be great to know that the date is not complete by having 1742-00-00 or something. If that does not work, sure, do -01-01 for now.

**Comment by kordianbruck** [comment]
@TimHenkelmann can you still do this please?

**Comment by TimHenkelmann** [comment]
it is currently implemented that we just take 01-01 if we do not have more information. Taking 00-00 is not accepted by the db. And regarding the date precision field I unfortunately do not have the time to dig deeper into that at the moment.

**Comment by kordianbruck** [comment]
Cool, then we can close this.
