### ISSUE TITLE
Add worldcat output to db population in cli.js

### ISSUE THREAD

**Issue by TimHenkelmann** [MusicConnectionMachine/StructuredData#74]
Add worldcat output to db population in cli.js

**Comment by sacdallago** [comment]
Is this done? 🤔

**Comment by kordianbruck** [comment]
I think it is: https://github.com/MusicConnectionMachine/StructuredData/blob/develop/cli.js#L52

**Comment by TimHenkelmann** [comment]
Not yet done! The worldcat script is added but the output isn't populated to the db at the moment

**Comment by kordianbruck** [comment]
@TimHenkelmann is this still feasable to do, before we rerun the scraping?

**Comment by TimHenkelmann** [comment]
Currently at it, should be done by tonight/tomorrow morning(04.05)

**Comment by TimHenkelmann** [comment]
Implemented in #90, waiting for the PR to be merged.

**Comment by TimHenkelmann** [comment]
Closed as fixed!
