### ISSUE TITLE
Fix multiple instruments with same name

### ISSUE THREAD

**Issue by TimHenkelmann** [MusicConnectionMachine/StructuredData#75]
Currently, multiple instruments with the same name get generated even though this should be handled correctly in the connectArtistToInstruments function...

**Comment by sacdallago** [comment]
Any updates for this?

**Comment by TimHenkelmann** [comment]
Nope, no news

**Comment by sacdallago** [comment]
:D can you (or anyone here) make news happen @TimHenkelmann ? :) :) ❤️ ❤️

**Comment by kordianbruck** [comment]
Yes, please make @sacdallago happy <3 :dancer: :man_dancing:

**Comment by felixschorer** [comment]
This doesn't impact @MusicConnectionMachine/group-2 as our filters are either hash based or eliminate duplicates when when inserting terms.

**Comment by TimHenkelmann** [comment]
fixed in #88
