### ISSUE TITLE
Model

### ISSUE THREAD

**Issue by simonzachau** [MusicConnectionMachine/StructuredData#8]
@MusicConnectionMachine/group-1 & @MusicConnectionMachine/group-2 

Have you thought about how the data model of the entities is going to look like? We would like to build on it for our relationship algorithms in the near future.

**Comment by Henni** [comment]
This was posted a while back on gitter: https://imgur.com/a/2gRzu

**Comment by simonzachau** [comment]
@Henni: what in this image is coming from Project A? Some parts look more like relationships than entities, which is our job. E.g. wife, children, students are likely going to not be filled by A because it's a relation? It'd be nice to have an official documentation of what we get, then we add the relationships on top of it.

**Comment by Henni** [comment]
I would be surprised if team1 wouldn't find any relationships. And of course they should store them instead of just dropping them. There is no point in doing this twice.
Also team3&4 mostly concentrate on relationship extraction from text. Team1 has structured data like this: http://imslp.org/wiki/List_of_works_by_Wolfgang_Amadeus_Mozart
Relationship extraction won't be able to detect these connections easily so we have to rely on team1 to import them.

**Comment by metavaults** [comment]
@MusicConnectionMachine/group-3 and @MusicConnectionMachine/group-4 
How do you expect the data from us to be?

@MusicConnectionMachine/group-2 guys, how do you expect the vocabulary we provide should look like?

**Comment by simonzachau** [comment]
@LukasNavickas I think you are going to extract entities and maybe you are going to find additional attributes for those entities, which you are going to save, too, instead of dropping it (like @Henni suggested). Our job is to find relationships in texts, that occasionally overlaps the mentioned attributes. So it's good for us to know the model, but for now we have no exact expectations ;-).

**Comment by kordianbruck** [comment]
@LukasNavickas whats the update here? Did you implement the models?

**Comment by TimHenkelmann** [comment]
@kordianbruck The models have been created in the api project. Should we provide a separate documentation for them?

**Comment by kordianbruck** [comment]
@TimHenkelmann no, but please make sure all of your code is properly documented!

**Comment by Gillian0023** [comment]
@TimHenkelmann  Thanks for your documentation !
MusicConnectionMachine/api#28

**Comment by TimHenkelmann** [comment]
closing this issue as this is done in the api project
