### ISSUE TITLE
Rework musicbrainz scrape execution order

### ISSUE THREAD

**Issue by TimHenkelmann** [MusicConnectionMachine/StructuredData#81]
Since implementing IP-rotation with proxys is kind of an overkill, we should restructure the scrape order of artists, works and releases. 
Currently, they are all scraped at the same time, each with 3 seconds delay per request. In about 10%-20% of the cases, this leads to blocked requests because musicbrainz only allows 1 request per second.

**Comment by kordianbruck** [comment]
Ah, I see. Ok yes, you need to scrape these in sequence.

**Comment by TimHenkelmann** [comment]
Implemented in #84

**Comment by ShilpaGhanashyamGore** [comment]
Closing the issue
